Updating assignment
chamatheapp/chama-frontend-assignment pull request #15
Opened 2021-02-03 18:38 UTC by ribeiroguilherme

2021-02-03 18:55 UTC, guiluisaa requested changes

2021-02-03 18:55 UTC, guiluisaa commented on README.md
>  The web app must have two pages:
Here you could be more assertive like:

`The web app must have two diferentes pages/routes:`

2021-02-03 18:55 UTC, guiluisaa commented on README.md
> +- CSS (styled-components, CSS modules, or plain CSS/SASS)
Add `Less` too.

`CSS/SASS/LESS`

2021-02-05 14:14 UTC, guiluisaa approved these changes

2021-02-05 14:59 UTC, peter-nezhnov approved these changes
changes are fine. I don't think it will teach people to read. But let's try.

2021-02-05 15:27 UTC, merged